### ISSUE TITLE
Add Time Conflict to Courses

### ISSUE THREAD

**Issue by VoThai** [mobileappdevhm/dev-team-5-webapp#31]
Notifies the student if a course is at the same time on antoher department or in his home department. If so the course can't be chosen and won't be set into the favourites list

**Comment by VoThai** [comment]
Time Conflict done. 

Improve Output Message, Need some Testing.

**Comment by ShaggyBlanco** [comment]
The "check for time conflict" feature moved to "favorites" page. Logically a user must verify that all selected courses in "favorites" don't clash with each other in terms of schedule. 

Therefore, when this feature is called, a small report window  would pop up and show either no text or a list of conflicts should some courses clash with each other. This windows can be closed when the user is done with reviewing.

**Comment by VoThai** [comment]
Done
